#!/bin/bash

set -x
export PATH="/usr/lib/ruby/gems/1.8/bin:$PATH"

[ -f failed.txt ] && rm failed.txt
[ -d BUILD ] || mkdir -p BUILD

for gem in `cat gem-list | grep -v "#" `
do
	version=`echo $gem | awk -F':' '{print $2}'`
	basename=`echo $gem | awk -F':' '{print $1}'`
	cd BUILD
	if [ x$version == 'x' ]; then
		echo "Building latest $basename"
		fpm -t rpm -s gem -a noarch $gem
		RETVAL=$?
	else
		echo "Building $basename version $version"
		fpm -t rpm -s gem -v $version -a noarch $basename
		RETVAL=$?
	fi
	echo "Build of $basename returned with $RETVAL"
	if [  $RETVAL -ne 0 ];
    echo $basename >> ../failed.txt
  fi
	cd ../
done
if [ -d ARTIFACTS ]
then
    rm -rf ARTIFACTS
fi
mkdir ARTIFACTS
mv BUILD/*.rpm ARTIFACTS
rm -rf BUILD

errcount=`cat failed.txt | wc -l`
if [ $errcount -gt 0 ]; then
  exit 1;
fi;
