#!/bin/bash

set -x
export PATH="/usr/lib/ruby/gems/1.8/bin:$PATH"

[ -f failed.txt ] && rm failed.txt
[ -d BUILD ] || mkdir -p BUILD

while read gem
do
	version=`echo $gem    | cut -d':' -f 2 `
	basename=`echo $gem   | cut -d':' -f 1 `
  extra_args=`echo $gem | cut -d':' -f 3- `
	cd BUILD
	if [ x$version == 'x' ]; then
		echo "Building latest $basename"
		eval fpm -t rpm -s gem -a noarch $extra_args $basename
		RETVAL=$?
	else
		echo "Building $basename version $version"
		fpm -t rpm -s gem -v $version -a noarch $extra_args $basename
		RETVAL=$?
	fi
	echo "Build of $basename returned with $RETVAL"
	if [  $RETVAL -ne 0 ]; then
    echo $basename >> ../failed.txt
  fi
	cd ../
done < <(cat gem-list | grep -v '^#')

if [ -d ARTIFACTS ]
then
    rm -rf ARTIFACTS
fi
mkdir ARTIFACTS
mv BUILD/*.rpm ARTIFACTS
rm -rf BUILD

errcount=`cat failed.txt | wc -l`
if [ $errcount -gt 0 ]; then
  exit 1;
fi;
